//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopter()
        {
            this.Adopter_Contract = new HashSet<Adopter_Contract>();
            this.Adoptions = new HashSet<Adoption>();
            this.Adopter_Relative = new HashSet<Adopter_Relative>();
            this.Foster_Care_Parent = new HashSet<Foster_Care_Parent>();
        }
    
        public int Adopter_ID { get; set; }
        public string Adopter_Name { get; set; }
        public string Adopter_Surname { get; set; }
        public string Adopter_Email { get; set; }
        public Nullable<int> Title_ID { get; set; }
        public string Adopter_Address { get; set; }
        public string Adopter_PostalAddress { get; set; }
        public string Adopter_HomeNumber { get; set; }
        public string Adopter_WorkNumber { get; set; }
        public string Adopter_CellNumber { get; set; }
        public string Adopter_CarRegistartion_Number { get; set; }
        public string Adopter_Employer { get; set; }
        public Nullable<int> Adopter_Status_ID { get; set; }
        public Nullable<int> Amount_of_Family_Memebers { get; set; }
        public Nullable<int> No_of_Children { get; set; }
        public Nullable<int> Age_of_Children { get; set; }
        public Nullable<bool> Property_Securely_Closed { get; set; }
        public Nullable<bool> Properyty_Include_Pool { get; set; }
        public Nullable<bool> Pool_Secured { get; set; }
        public Nullable<bool> Animal_Shelter_Available { get; set; }
        public Nullable<bool> Sick_Animal { get; set; }
        public string Sick_Animal_Diagnosis { get; set; }
        public string Animal_Sleep_Location { get; set; }
        public Nullable<bool> Given_Animal_Away { get; set; }
        public string HomeCheck_Suburb { get; set; }
        public string Type_of_House { get; set; }
        public Nullable<bool> Adopted_Before { get; set; }
        public Nullable<bool> Complex_or_Flat { get; set; }
        public Nullable<bool> Animal_Allowed { get; set; }
        public string Animal_Captivity { get; set; }
        public Nullable<bool> Animal_Vaccines_Updated { get; set; }
    
        public virtual Title Title { get; set; }
        public virtual Adopter_Status Adopter_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopter_Contract> Adopter_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopter_Relative> Adopter_Relative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foster_Care_Parent> Foster_Care_Parent { get; set; }
    }
}
