//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopter_Relative
    {
        public int Relative_ID { get; set; }
        public string Relative_Name { get; set; }
        public string Relative_Surname { get; set; }
        public string Relative_Email { get; set; }
        public string Relative_Address { get; set; }
        public string Relative_PostalAddress { get; set; }
        public string Relative_Home_Tel { get; set; }
        public string Relative_Work_Tel { get; set; }
        public string Relative_Cell { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> Adopter_ID { get; set; }
    
        public virtual Adopter Adopter { get; set; }
    }
}
