//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capture_Medical_Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capture_Medical_Card()
        {
            this.Animal_Treatment = new HashSet<Animal_Treatment>();
        }
    
        public int Capture_Medical_Card_ID { get; set; }
        public string Diagnosis_Details { get; set; }
        public Nullable<System.DateTime> Capture_Medical_Card_Date { get; set; }
        public Nullable<System.DateTime> Capture_Medical_Card_NextAppointment_Date { get; set; }
        public Nullable<int> Vet_Appoint_Line_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_Treatment> Animal_Treatment { get; set; }
        public virtual Vet_Appointment_Line Vet_Appointment_Line { get; set; }
    }
}
