//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_()
        {
            this.Customer_Event = new HashSet<Customer_Event>();
        }
    
        public int Event_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_StartTime { get; set; }
        public Nullable<System.DateTime> Event_EndTime { get; set; }
        public Nullable<int> Event_Guest_Number { get; set; }
        public Nullable<decimal> Event_Ticket_Price { get; set; }
        public string Event_Location { get; set; }
        public string Event_Description { get; set; }
        public Nullable<int> Event_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Event> Customer_Event { get; set; }
        public virtual Event_Type Event_Type { get; set; }
    }
}
