//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Line
    {
        public int Donation_Line_ID { get; set; }
        public Nullable<decimal> Donation_Quantity { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Donation_ID { get; set; }
        public Nullable<int> Donation_Type_ID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Donation_Type Donation_Type { get; set; }
    }
}
