//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vet_Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vet_Appointment()
        {
            this.Vet_Appointment_Line = new HashSet<Vet_Appointment_Line>();
        }
    
        public int Vet_Appointment_ID { get; set; }
        public Nullable<int> Vet_ID { get; set; }
    
        public virtual Veterinarian Veterinarian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vet_Appointment_Line> Vet_Appointment_Line { get; set; }
    }
}
