//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wollies_ShelterEntities1 : DbContext
    {
        public Wollies_ShelterEntities1()
            : base("name=Wollies_ShelterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adopter> Adopters { get; set; }
        public virtual DbSet<Adopter_Contract> Adopter_Contract { get; set; }
        public virtual DbSet<Adopter_Relative> Adopter_Relative { get; set; }
        public virtual DbSet<Adopter_Status> Adopter_Status { get; set; }
        public virtual DbSet<Adoption> Adoptions { get; set; }
        public virtual DbSet<Adoption_Status> Adoption_Status { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Animal_Breed> Animal_Breed { get; set; }
        public virtual DbSet<Animal_Kennel_History> Animal_Kennel_History { get; set; }
        public virtual DbSet<Animal_Status> Animal_Status { get; set; }
        public virtual DbSet<Animal_Treatment> Animal_Treatment { get; set; }
        public virtual DbSet<Animal_Type> Animal_Type { get; set; }
        public virtual DbSet<Audit_Log> Audit_Log { get; set; }
        public virtual DbSet<Capture_Medical_Card> Capture_Medical_Card { get; set; }
        public virtual DbSet<CrossBreed> CrossBreeds { get; set; }
        public virtual DbSet<Customer_Event> Customer_Event { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Donation_Line> Donation_Line { get; set; }
        public virtual DbSet<Donation_Type> Donation_Type { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Emp_Kennel> Emp_Kennel { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Event_> Event_ { get; set; }
        public virtual DbSet<Event_Schedule> Event_Schedule { get; set; }
        public virtual DbSet<Event_Type> Event_Type { get; set; }
        public virtual DbSet<Foster_Care> Foster_Care { get; set; }
        public virtual DbSet<Foster_Care_Parent> Foster_Care_Parent { get; set; }
        public virtual DbSet<HomeCheck> HomeChecks { get; set; }
        public virtual DbSet<Kennel> Kennels { get; set; }
        public virtual DbSet<Microchip> Microchips { get; set; }
        public virtual DbSet<Packaging_Type> Packaging_Type { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Stock_Type> Stock_Type { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Unit_Type> Unit_Type { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Vet_Appointment> Vet_Appointment { get; set; }
        public virtual DbSet<Vet_Appointment_Line> Vet_Appointment_Line { get; set; }
        public virtual DbSet<Veterinarian> Veterinarians { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<Volunteer_Hours> Volunteer_Hours { get; set; }
        public virtual DbSet<Volunteer_Work_Type> Volunteer_Work_Type { get; set; }
    }
}
